### ISSUE TITLE
Refresh failed: redisc: all nodes failed

### ISSUE THREAD

**Issue by LeJane** [mna/redisc#28]

**Comment by mna** [comment]
Hello, 

This is the error returned when no node could be contacted, this is likely not a problem with redisc but with the network/connection configuration. However, I notice that this swallows the specific error messages, something I'll address so that in the future it returns "all nodes failed" followed by the specific error(s) as returned by the connection attempts.

Hope this helps,
Martin

**Comment by mna** [comment]
The error message change has been published in v1.1.6, following the "all nodes failed" message is the list of error messages returned for each attempted node.
