### ISSUE TITLE
is HMSET operation supported, when using redis clustermode enabled?

### ISSUE THREAD

**Issue by prabhu352** [mna/redisc#35]
currently i am using redis with cluster mode enabled with following config,
cluster := redisc.Cluster{
		StartupNodes: []string{"******.clustercfg.use1.cache.amazonaws.com:6379"},
		DialOptions:  []redis.DialOption{redis.DialConnectTimeout(5 * time.Second)},
		CreatePool:   createPool,
	}

and doing the following operation:
hmsetargs := make([]interface{}, len(tags)+1)
	hmsetargs[0] = constant.ROOT_KEY
	for k, v := range tags {
		hmsetargs = append(hmsetargs, k, v)
	}
	tempcon := pool.Get()
	// make it handle redirections automatically
	conntoset, err := redisc.RetryConn(tempcon, 3, 100*time.Millisecond)
	if err != nil {
		log.Error().Err(err).Msg("RetryConn failed: ")
	}

	_, err = conntoset.Do("hmset", hmsetargs...)
	tempcon.Close()

and i am seeing this error:
"error":"ERR wrong number of arguments for HMSET"

**Comment by mna** [comment]
Hello,

Yes it is supported, that command is part of the test suite of redisc (https://github.com/mna/redisc/blob/master/cluster_test.go#L232). Note that according to the redis website, as of redis 4.0 it is now considered deprecated (in favor of HSET, https://redis.io/commands/hmset).

Looking at your code, I believe the issue is that you create your slice with a predefined **length** (as opposed to **capacity**) and then you append to it, so a number of arguments are just nil:

```
hmsetargs := make([]interface{}, len(tags)+1)
// vs
hmsetargs := make([]interface{}, 0, len(tags)+1)
// although note that even that is not quite correct, because
// for each tag you actually append *2* values, so this would be best (untested):
hmsetargs := make([]interface{}, 0, (2 * len(tags))+1)
// ...

// however now you have a slice of 0-len and N-capacity, so you must change
hmsetargs[0] = constant.ROOT_KEY
// which would panic, to
hmsetargs = append(hmsetargs, constant.ROOT_KEY)
```

Hope this helps,
Martin
