### ISSUE TITLE
Does it support pipeline in cluster mode

### ISSUE THREAD

**Issue by UnderTreeTech** [mna/redisc#36]

**Comment by mna** [comment]
Hello,

It does, via the `Conn.Send` method https://pkg.go.dev/github.com/mna/redisc?utm_source=godoc#Conn.Send (similar to how the redigo package handles pipelining: https://pkg.go.dev/github.com/gomodule/redigo/redis#hdr-Pipelining). Though of course the pipelined commands must operate on keys that belong to the same cluster node.

Hope this helps,
Martin

**Comment by UnderTreeTech** [comment]
Does it return error if keys are not located in same slot or cluster node? @mna

**Comment by mna** [comment]
It will, when the pipelined commands are executed (i.e. on the call to `Do` or on calls to `Receive` after `Flush` has been sent).

**Comment by UnderTreeTech** [comment]
So I have to use `SplitBySlot` to group same keys to a given slot before using batch commands such as pipeline, mget?

**Comment by mna** [comment]
Technically, the answer is yes. However, it is rarely a good idea to send a batch of commands with arbitrary keys in cluster mode, and if the keys have not been carefully chosen for Redis Cluster, they might not batch well even with SplitBySlot (i.e. you could end up with a single command per "batch"). Ideally, you should carefully design your keys so that they play well with the cluster and optimize the number of network calls you make when processing related keys (e.g. keys related to a given user id).

If you haven't already, I suggest you read the Redis docs on cluster, especially the part on "Migrating to Redis Cluster" where it mentions the concerns with multiple keys operations/transactions: https://redis.io/topics/cluster-tutorial#migrating-to-redis-cluster

And some more information about how to address this using hash tags in the cluster spec: https://redis.io/topics/cluster-spec#keys-hash-tags

Hope this helps,
Martin
