### ISSUE TITLE
READONLY command on every requests

### ISSUE THREAD

**Issue by Xanvial** [mna/redisc#47]
Hello,
I'm currently starting to implement this library on our system. Using default cluster implementation with 3 masters and 3 replicas. One of the main things that I want to implement is using only replica servers for all readonly command. Based on the implementation of redisc, this can be done by calling `redisc.ReadOnlyConn(conn)` before calling each readonly command.

This approach works, but on redis monitor it seems the `READONLY` command is called on every request. This doesn't seem efficient (considering on high RPS this will add not-insignificant latency), so is it possible to change the behavior to only call `READONLY` at the start of connection creation?

I've tried creating separate pool for readonly process, and take the connection from that, but so far it doesn't work as I expected. Or is there anything else I can try?

**Comment by mna** [comment]
Hello Alvian,

That's a good point, and not something that can really be done at the moment (the closest thing I can think of is in the `Cluster.CreatePool` function that returns a `*redis.Pool`, use the `TestOnBorrow` field of the pool to make that `READONLY` command call, but then again there's no easy way in this function to know that the connection is requested for a replica and that the `READONLY` command has not already been emitted for that connection).

At the moment, `redisc` emits it as needed each time a read-only connection is used, and cals `READWRITE` before returning the connection to the pool in case the replica gets promoted to a primary, so that connections returned by the pool are always reset to "vanilla" state. That's probably something that can be improved upon but requires some thought and good design.

Thanks for raising this! I'll try to create a proposal issue for it (as I've done for a few other features I'd like to add), so it can be addressed in a future version.

Martin

**Comment by Xanvial** [comment]
thanks
